runtime: python37


handlers:
- url: /static/css
  static_dir: static/css
  secure: always
- url: /static/js
  static_dir: static/js
  secure: always
- url: /static/img
  static_dir: static/img
  secure: always
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
